language: python
python:
 - "3.8"

services:
  - docker
  

before_script: 
 - 'cd Django/recipe-app-api/'
 - 'pip install docker-compose'
script:
  - docker-compose run app sh -c "python manage.py test && flake8"