language: python
python:
 - "3.6"

services:
  - docker
  
before_install: cd Django/recipe-app-api/
before_script: 
 - echo 'pip install docker-compose'
script: 
  - docker-compose run app sh -c "python manage.py test && flake8"